apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/ibm-cloud-architecture/refarch-eda-store-simulator.git
  labels:
    app.kubernetes.io/name: store-simulator
    app.openshift.io/runtime: quarkus
  name: store-simulator
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: store-simulator
  type: ClusterIP