apiVersion: v1
kind: ConfigMap
metadata:
  name: store-simulator-cm
data:
  APP_VERSION: 0.0.7
  APP_TARGET_MESSAGING: IBMMQ
  MQ_HOST: store-mq-ibm-mq.smq-dev.svc
  MQ_PORT: "1414"
  MQ_QMGR: QM1 
  MQ_QUEUE_NAME: items
  MQ_CHANNEL: DEV.APP.SVRCONN